FROM python:3-alpine

### ATTENZIONE ###
# Aggiungere i file di requirement e del codice python tramite il comando ADD

# Eseguire con il RUN il comando di pip install dei requirement 'pip install -r path/to/requirements.txt'

# Utilizzare come comando di esecuzione del container (CMD) 'python path/to/bases.py'

# https://docs.docker.com/engine/reference/builder/