FROM python:3-alpine

### ATTENZIONE ###
# Aggiungere i file di requirements e del codice python

# Eseguire il pip install dei requirements ('pip install -r path/to/requirements.txt')

# Utilizzare come entry di esecuzione del container il seguente comando 'python path/to/ds1KyberCannon.py'

# https://docs.docker.com/engine/reference/builder/
